# Generated by Django 6.0.2 on 2026-05-14 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', 'Food & Drink'), ('TRAVEL', 'Travel'), ('HOUSING', 'Housing'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Utilities'), ('OTHER', 'Other'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('alert_thresholds_sent', models.JSONField(default=dict)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'group', 'category', 'month', 'year'), name='unique_budget_per_user_category_time')],
            },
        ),
    ]
