# Generated by Django 6.0.2 on 2026-07-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='trip',
        ),
    ]
