# Generated by Django 6.0.2 on 2026-02-19 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_receipt_url_expense_trip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvers', models.ManyToManyField(blank=True, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='expenses.expense')),
            ],
        ),
    ]
