# Generated by Django 6.0.2 on 2026-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_approvalworkflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settlement',
            old_name='debtor',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='settlement',
            old_name='creditor',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Drink'), ('TRAVEL', 'Travel'), ('HOUSING', 'Housing'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
