# Generated by Django 6.0.2 on 2026-02-24 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_settlement_count_alter_user_reliability_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliabilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
