# Generated by Django 6.0.2 on 2026-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reliabilityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
    ]
